# -*- coding: utf-8 -*-
#
# BirdCLEF documentation build configuration file, created by
# sphinx-quickstart.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# Adiciona o diretório do seu código ao sys.path para que o Sphinx possa encontrá-lo.
# Altere '../caminho/para/seu/codigo' para o caminho correto do seu código.
sys.path.insert(0, os.path.abspath('../'))

# -- General configuration -----------------------------------------------------

# Extensões necessárias para documentação automática e suporte a docstrings.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',  # Para suportar docstrings estilo Google e NumPy
    'nbsphinx',
]

templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'

project = u'BirdCLEF'
version = '0.1'
release = '0.1'

exclude_patterns = ['_build', 'Thumbs.db']

pygments_style = 'sphinx'

# -- Options for HTML output ---------------------------------------------------

# Alterando para um tema mais moderno (opcional)
html_theme = 'alabaster'

html_static_path = ['_static']

# Outras configurações do HTML podem ser ajustadas aqui, conforme necessário.

# -- Options for LaTeX output --------------------------------------------------
# Aqui você pode ajustar as configurações de saída do LaTeX, se necessário.

# -- Outras configurações ------------------------------------------------------
# Adicione qualquer outra configuração específica que seu projeto possa requerer.
